### ISSUE TITLE
建议增加反链面板查看

### ISSUE THREAD

**Issue by ioypl** [Achuan-2/siyuan-plugin-blockref-footnote#1]

**Comment by Achuan-2** [comment]
1. 脚注放在当前文档，本身反链面板就能看到
2. 脚注放在其他文档，可以在脚注内容模板，添加原块块引即可。现在默认模板用的是块超链接，可以改为块引样式

**Comment by ioypl** [comment]
> 1. 脚注放在当前文档，脚注引用使用块引样式，本身反链面板就能看到所有的脚注引用
> 2. 脚注放在其他文档，可以在脚注内容模板，添加原块块引即可。现在默认模板用的是块超链接，可以改为块引样式，就能在反链面板看到所有的脚注内容

纯新手，大佬给我演示下

**Comment by ioypl** [comment]
> 1. 脚注放在当前文档，脚注引用使用块引样式，本身反链面板就能看到所有的脚注引用
> 2. 脚注放在其他文档，可以在脚注内容模板，添加原块块引即可。现在默认模板用的是块超链接，可以改为块引样式，就能在反链面板看到所有的脚注内容

纯新手，大佬能否给我演示一下，谢谢

**Comment by ioypl** [comment]
> Reference in ne

![PixPin_2024-11-21_13-08-19](https://github.com/user-attachments/assets/4c123c5d-16eb-45d7-b0e0-dd6e8747209f)
就是在当前文档的反链面板，查看注脚内容

**Comment by ioypl** [comment]
> 我不清楚你要在反链面板查看什么 第一种方法，就是插件默认的设置，你自己打开反链面板查看是不是你要的 第二种方法，在脚注内容模板添加指向原块的块引`((${refID} "↩️"))`
![PixPin_2024-11-21_13-13-38](https://github.com/user-attachments/assets/05eb3880-03fd-4797-b683-5dd386f1bd12)
就这张图，我先在反链面板查看“知道”，这个注脚内容

**Comment by Achuan-2** [comment]
那按照我讲的第二种方法，插件的设置里给脚注内容模板添加原块链接即可

**Comment by ioypl** [comment]
> ((${refID} "↩️"))

![PixPin_2024-11-21_14-08-33](https://github.com/user-attachments/assets/bff82009-5087-49c7-8f5b-227b6687c216)
tian'j
添加了后效果如下，没太明白。

**Comment by Achuan-2** [comment]
说的是模板改成这样
```
{{{row
> ${selection} ((${refID} "↩️"))

${content}
}}}
{: style="border: 2px dashed var(--b3-border-color);"}
```

**Comment by ioypl** [comment]
> 说的是插件设置里的模板改成这样
> 
> ```
> {{{row
> > ${selection} ((${refID} "↩️"))
> 
> ${content}
> }}}
> {: style="border: 2px dashed var(--b3-border-color);"}
> ```

万分感谢
![PixPin_2024-11-21_14-37-13](https://github.com/user-attachments/assets/9ac93b20-01cd-4852-9c43-fd35708801a8)
设置后效果如图，想请问，反链中怎么才能显示注脚内容“我爱添加注脚”

**Comment by Achuan-2** [comment]
思源笔记的反链面板自动聚焦，只显示当前块
要在反链里默认展开其他块，只能做到展开子块，要展开子块，只能列表项是块引，不能有其他文字，这样才会自动展开
比如改为这样
```
-  ((${refID} "${selection}"))
   {{{row
   ${content}
   }}}
```
