### ISSUE TITLE
选中文本添加自定义样式

### ISSUE THREAD

**Issue by Achuan-2** [Achuan-2/siyuan-plugin-blockref-footnote#10]
支持对重叠文字添加不同脚注时，能保留不同脚注的选中文字样式，删除脚注时，只删除当前脚注选中的文本，不影响其他脚注选中文字的样式

解决方案：给custom-footnote-selected-text后面添加id，这样只删除当前脚注的选中文本样式，不删除别的，也不会因为重叠添加脚注，造成选中文本样式丢失

**Comment by Achuan-2** [comment]
https://github.com/Achuan-2/siyuan-plugin-blockref-footnote/commit/70eab29b5785e4dd4e12a74dbe6c0bc205bc4a9f

**Comment by leommjj** [comment]
文本样式不会随着脚注删除而删除，自带的元素清理工具无效。

**Comment by Achuan-2** [comment]
删除脚注的时候要右键删除
或者用命令面板，可以清除样式

光标删除脚注，文本样式自动删除，短期没时间优化
