### ISSUE TITLE
写味主题下注脚不显示文字

### ISSUE THREAD

**Issue by ioypl** [Achuan-2/siyuan-plugin-blockref-footnote#13]
![PixPin_2024-11-25_23-41-42](https://github.com/user-attachments/assets/d5da5645-45ca-4d11-bc42-b9d5f3d2d37c)

**Comment by Achuan-2** [comment]
> ![PixPin_2024-11-25_23-41-42](https://private-user-images.githubusercontent.com/108966237/389601290-d5da5645-45ca-4d11-bc42-b9d5f3d2d37c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI1NTAyMzYsIm5iZiI6MTczMjU0OTkzNiwicGF0aCI6Ii8xMDg5NjYyMzcvMzg5NjAxMjkwLWQ1ZGE1NjQ1LTQ1Y2EtNGQxMS1iYzQyLWI5ZDVmM2QyZDM3Yy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyNVQxNTUyMTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wYzZhODA2NWZmMTkyMDI0MzA3OTA3OTE5ZDkyM2MyOWRlZmE4MjAyMmNiOWZlNThlNWNmODEzMjY5ZjNkMDA3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.8jHoBA4XK9WKXfS-PtqmASakNGmXShfTccbVrADnaS8)

因为该主题的font5背景颜色和默认文字颜色完全一样

**Comment by Achuan-2** [comment]
可以参考本插件更新的readme，自行修改css

**Comment by Achuan-2** [comment]
脚注引用的样式默认改为蓝色背景+蓝色字体颜色

**Comment by Achuan-2** [comment]
https://github.com/Achuan-2/siyuan-plugin-blockref-footnote/commit/53c0eb7ff12a74919d04f319cfef5804a01ef357

**Comment by ioypl** [comment]
> [53c0eb7](https://github.com/Achuan-2/siyuan-plugin-blockref-footnote/commit/53c0eb7ff12a74919d04f319cfef5804a01ef357)

感谢！！

**Comment by Jiangshuon** [comment]
大佬，css不是这样的吗？怎么写味主题还是这样呢

.protyle-wysiwyg [data-node-id] span[custom-footnote] {
    background-color: var(--b3-card-info-background);
    color: var(--b3-card-info-color) !important; 
    border: none !important;
    margin: 0 1px;
    border-radius: 3px;
}

**Comment by Jiangshuon** [comment]
![image](https://github.com/user-attachments/assets/92a0076a-f01b-4c2d-a583-5dabd0b0f331)

**Comment by Achuan-2** [comment]
> ![image](https://private-user-images.githubusercontent.com/67137548/390998493-92a0076a-f01b-4c2d-a583-5dabd0b0f331.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI4NjY5NzcsIm5iZiI6MTczMjg2NjY3NywicGF0aCI6Ii82NzEzNzU0OC8zOTA5OTg0OTMtOTJhMDA3NmEtZjAxYi00YzJkLWE1ODMtNWRhYmQwYjBmMzMxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI5VDA3NTExN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY2NDI4OWJmZjcxOWVkMzUyNzg2OWYwYWIyYjkzNmVhNjMzZGNiMjgwNTNlZGU5OGQxNzhmNGU0YWZkOGQ3MmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.soaj06HfdMPUNwTNJBamJjmRosVfXRaja6hWvp5gHW8)

因为写味主题设置了块引叠加上标，就是黑色背景，我不知道为什么他要这样设置，要么你学写味主题的css样式重写，要么你把代码片段里的color去掉，用白色字体

**Comment by Achuan-2** [comment]
下个版本我干脆默认不设置css样式了，需要的自己改

**Comment by Jiangshuon** [comment]
多谢大佬，我试试
