### ISSUE TITLE
新版1.16带外链模板，注脚内容会丢失

### ISSUE THREAD

**Issue by ioypl** [Achuan-2/siyuan-plugin-blockref-footnote#18]
![PixPin_2024-12-01_09-36-31](https://github.com/user-attachments/assets/d5087c34-1e95-4c70-b610-f93c461db920)

**Comment by Achuan-2** [comment]
模板是什么

**Comment by ioypl** [comment]
> 模板是什么

-  ((${refID} "${selection}"))

  {{{row
  ${content}
  }}}

**Comment by Achuan-2** [comment]
无法复现
