### ISSUE TITLE
使用模板，每行都多一处空行出来

### ISSUE THREAD

**Issue by ioypl** [Achuan-2/siyuan-plugin-blockref-footnote#20]
![PixPin_2024-12-01_15-32-06](https://github.com/user-attachments/assets/97999a99-e348-456a-8cbf-dabdd5320695)
![PixPin_2024-12-01_15-33-04](https://github.com/user-attachments/assets/c7589338-086f-429d-98cd-8434be856062)

**Comment by ioypl** [comment]
1.17最新版

**Comment by Achuan-2** [comment]
模板不对，列表与超级块需要有一个空行，不然都会认为是列表项的内容

**Comment by ioypl** [comment]
> 模板不对， 列表与超级块需要有一个空行，不然都会认为是列表项的内容 自己检查模板最后有没有多余空行

![PixPin_2024-12-01_16-29-50](https://github.com/user-attachments/assets/edd6adc4-44e6-4b19-9601-6a9ee8579423)
使用你g给的模板，模版中没有多余空行，但是还是出现这个问题。

**Comment by Achuan-2** [comment]
复制这个看看，我自己测试是没问题的。只看图片是不确定你模板里有没有零宽字符的
```
- ((${refID} "${selection}"))

  {{{row
  ${content}
  }}}
```

**Comment by ioypl** [comment]
> 复制这个看看，我自己测试是没问题的。只看图片是不确定你模板里有没有零宽字符的
> 
> ```
> - ((${refID} "${selection}"))
> 
>   {{{row
>   ${content}
>   }}}
> ```

现在这个就正常了

**Comment by Achuan-2** [comment]
> > 复制这个看看，我自己测试是没问题的。只看图片是不确定你模板里有没有零宽字符的
> > ```
> > - ((${refID} "${selection}"))
> > 
> >   {{{row
> >   ${content}
> >   }}}
> > ```
> 
> 现在这个就正常了

那可能就是末尾有零宽字符，零宽字符只能用sublime text等文本编辑器才能显示出来
