### ISSUE TITLE
【Bug】当在设置里开启只读模式后，添加脚注后脚注弹窗不可写入

### ISSUE THREAD

**Issue by lsb226** [Achuan-2/siyuan-plugin-blockref-footnote#30]
视频如下
![20241206_151152](https://github.com/user-attachments/assets/733488ab-d248-4d3c-a181-5036b347739e)

**Comment by lsb226** [comment]
设置里开启关闭只读模式，脚注弹窗是可以写入的

**Comment by Achuan-2** [comment]
暂时不知道怎么解决，只能把面包屑加上去，自己手动解锁，因为块引浮窗也是需要自己手动解锁才能编辑的

**Comment by Achuan-2** [comment]
https://github.com/siyuan-note/siyuan/issues/13391

思源v3.1.15可以支持enable protyle

**Comment by lsb226** [comment]
完美，等更新
