### ISSUE TITLE
注脚bug

### ISSUE THREAD

**Issue by ioypl** [Achuan-2/siyuan-plugin-blockref-footnote#32]
- ((${refID} "${selection}"))

  {{{row
  ${content}
  }}}
用的是上面这个模板。
![PixPin_2024-12-07_23-31-51](https://github.com/user-attachments/assets/8c3ad3b9-356c-4e42-a288-b0b31ccfbc3d)
chu
出现上面两个问题
1、弹出面板位置太靠下，不方便操作，要手动托到中间
2、注脚有一定概率没生成块引，且文本前出现莫名数字，pdf摘录文本必出现此bug，纯文本有一定概率出现，以前版本没出现过。

**Comment by Achuan-2** [comment]
暂时复现不出来

**Comment by ioypl** [comment]
> 和你的模板有关系，模板里用了块引语法，锚文本只能是纯文本，插件的selection变量是html文本，自然就乱掉了

那能解决吗？以前版本你给我这个模板就用着非常舒服

**Comment by Achuan-2** [comment]
下个版本用这个模板
```markdown
- ((${refID} "${selection:text}"))

  {{{row
  ${content}
  }}}
```

**Comment by ioypl** [comment]
> 下个版本用这个模板
> 
> ```
> - ((${refID} "${selection:text}"))
> 
>   {{{row
>   ${content}
>   }}}
> ```

1.29用这个模板，有英文引号的还是不行
![PixPin_2024-12-13_08-05-37](https://github.com/user-attachments/assets/c10a40b8-2718-41c3-b9ad-722564aebbe0)

**Comment by Achuan-2** [comment]
v1.3.0 已经修复
