### ISSUE TITLE
删除注脚后，不能自动恢复文本样式，不能删除注脚内容块。

### ISSUE THREAD

**Issue by ioypl** [Achuan-2/siyuan-plugin-blockref-footnote#8]

**Comment by Achuan-2** [comment]
1. 本插件是脚注插件，不是划词评论插件，推荐不设置选中文本的样式，选中文本样式只是为了加脚注的同时添加样式凸显，不是为了与脚注样式绑定，删除脚注，不会自动重置文本样式（另外这一点也非常麻烦，要做，只能用自定义样式，不能用思源内置的样式）
2. 删除脚注内容，是右键删除，直接删除脚注，不删除脚注内容
![PixPin_2024-11-23_19-14-22](https://github.com/user-attachments/assets/9aadd312-91ec-48b0-b43d-e9bf8fb80c47)

**Comment by Achuan-2** [comment]
v1.1.2  选中文本添加自定义样式，现在支持对重叠文字添加不同脚注时，能保留不同脚注的选中文字样式，删除脚注时，只删除当前脚注选中的文本，不影响其他脚注选中文字的样式
